# Generated by Django 5.1 on 2024-09-02 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='Имя')),
                ('first_login', models.DateTimeField(blank=True, null=True, verbose_name='Первый вход')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('points', models.IntegerField(default=0, verbose_name='Очки')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название буста')),
                ('type', models.CharField(max_length=15, verbose_name='Тип буста')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
                ('source', models.CharField(choices=[('level', 'Пройденнный уровень'), ('manually', 'Вручную')], max_length=8, verbose_name='Источник получения')),
                ('acquired_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Буст',
                'verbose_name_plural': 'Бусты',
                'ordering': ('id',),
            },
        ),
    ]
